/**
 * Structural role: "planet" = orbits the star (dwarf planets too), "moon" = orbits a planet,
 * "region" = a zone of many small bodies (asteroid belt)
 */
export type BodyType = "galaxy" | "star" | "planet" | "moon" | "spacecraft" | "region";

export type BodyCategory =
  | "Galaxy"
  | "Star"
  | "Terrestrial planet"
  | "Gas giant"
  | "Ice giant"
  | "Dwarf planet"
  | "Moon"
  | "Spacecraft"
  | "Asteroid belt";

export interface Stat {
  label: string;
  value: string;
}

export interface CelestialBody {
  id: number;
  type: BodyType;
  category: BodyCategory;
  name: string;
  map: string; // identifier, also used in the URL (?body=…)
  texture: string; // sphere texture in /public ("" when not rendered as a sphere)
  color: string; // marker color when the body is too small to see
  image: string; // card image in /public/images ("" → texture preview)
  radius: number; // km
  distanceFromParent: number; // km, fallback when orbital data is missing
  horizonsId: string;
  orbitId?: string; // key in orbits.json, defaults to horizonsId (barycenters for giant planets)
  /** The orbit is the barycenter's: shift by the big moon's pull (Earth–Moon, Pluto–Charon) */
  barycenter?: { satelliteId: string; massRatio: number };
  info: {
    mass: string;
    gravity: number;
    temperature: number;
    dayLength: string;
    yearLength: string;
    orbitalSpeed: number;
    axialTilt: number;
    poleRA?: number;  // Right Ascension of north pole (equatorial J2000, degrees)
    poleDec?: number; // Declination of north pole (equatorial J2000, degrees)
    spinW0?: number;    // Prime meridian angle at J2000 epoch (degrees)
    spinRate?: number;  // Rotation rate (degrees/day, negative = retrograde)
    eccentricity: number;
    magneticField: boolean;
    rings: boolean;
    atmosphere: string[];
    funFact: string;
  };
  /** Galaxy-only facts */
  galaxy?: { diameter: string; kind: string; stats: Stat[] };
  /** Spacecraft-only facts */
  mission?: { agency: string; launched: string; status: string; stats: Stat[] };
  /** Region-only facts (asteroid belt) */
  region?: { headline: Stat[]; stats: Stat[]; innerAU: number; outerAU: number };
  children: CelestialBody[];
}

/** Bodies without physical stats (spacecraft, regions): only the fun fact is shown */
function factOnlyInfo(funFact: string): CelestialBody["info"] {
  return {
    mass: "",
    gravity: 0,
    temperature: 0,
    dayLength: "",
    yearLength: "",
    orbitalSpeed: 0,
    axialTilt: 0,
    eccentricity: 0,
    magneticField: false,
    rings: false,
    atmosphere: [],
    funFact,
  };
}

export const SOLAR_SYSTEM: CelestialBody = {
  id: 0,
  type: "star",
  name: "Sun",
  map: "sun",
  texture: "2k_sun.jpg",
  category: "Star",
  color: "#ffcc55",
  image: "sun.webp",
  radius: 696340,
  distanceFromParent: 0,
  horizonsId: "10",
  info: {
    mass: "1.989 × 10³⁰ kg",
    gravity: 274,
    temperature: 5500,
    dayLength: "25.4 Earth days",
    yearLength: "225 million years",
    orbitalSpeed: 220,
    axialTilt: 7.25,
    poleRA: 286.13,
    poleDec: 63.87,
    spinW0: 84.176,
    spinRate: 14.1844,
    eccentricity: 0,
    magneticField: true,
    rings: false,
    atmosphere: ["H 73.46%", "He 24.85%"],
    funFact: "The Sun accounts for 99.86% of the total mass of the Solar System.",
  },
  children: [
    {
      id: 1,
      type: "planet",
      name: "Mercury",
      map: "mercury",
      texture: "2k_mercury.jpg",
      category: "Terrestrial planet",
      color: "#b8b1a8",
      image: "mercury.webp",
      radius: 2439.7,
      distanceFromParent: 57910000,
      horizonsId: "199",
      info: {
        mass: "3.301 × 10²³ kg",
        gravity: 3.7,
        temperature: 167,
        dayLength: "58d 15h",
        yearLength: "88 days",
        orbitalSpeed: 47.4,
        axialTilt: 0.03,
        poleRA: 281.01,
        poleDec: 61.41,
        spinW0: 329.5988,
        spinRate: 6.1385108,
        eccentricity: 0.2056,
        magneticField: true,
        rings: false,
        atmosphere: [],
        funFact: "Mercury's day is longer than its year — one solar day lasts 176 Earth days.",
      },
      children: [],
    },
    {
      id: 2,
      type: "planet",
      name: "Venus",
      map: "venus",
      texture: "2k_venus_surface.jpg",
      category: "Terrestrial planet",
      color: "#e6c98f",
      image: "venus.webp",
      radius: 6051.8,
      distanceFromParent: 108200000,
      horizonsId: "299",
      info: {
        mass: "4.867 × 10²⁴ kg",
        gravity: 8.87,
        temperature: 464,
        dayLength: "243 Earth days",
        yearLength: "225 days",
        orbitalSpeed: 35.0,
        axialTilt: 177.36,
        poleRA: 272.76,
        poleDec: 67.16,
        spinW0: 160.20,
        spinRate: -1.4813688,
        eccentricity: 0.0067,
        magneticField: false,
        rings: false,
        atmosphere: ["CO₂ 96.5%", "N₂ 3.5%"],
        funFact: "Venus rotates backwards compared to most planets, and its day is longer than its year.",
      },
      children: [],
    },
    {
      id: 3,
      type: "planet",
      name: "Earth",
      map: "earth",
      texture: "2k_earth_daymap.jpg",
      category: "Terrestrial planet",
      color: "#6fa8ff",
      image: "earth.webp",
      radius: 6371,
      distanceFromParent: 149600000,
      horizonsId: "399",
      orbitId: "3",
      barycenter: { satelliteId: "301", massRatio: 0.012150584 },
      info: {
        mass: "5.972 × 10²⁴ kg",
        gravity: 9.81,
        temperature: 15,
        dayLength: "23h 56m",
        yearLength: "365.25 days",
        orbitalSpeed: 29.8,
        axialTilt: 23.44,
        poleRA: 0.00,
        poleDec: 90.00,
        spinW0: 190.147,
        spinRate: 360.9856235,
        eccentricity: 0.0167,
        magneticField: true,
        rings: false,
        atmosphere: ["N₂ 78%", "O₂ 21%", "Ar 0.9%"],
        funFact: "Only known planet to harbor life. 71% of its surface is covered by water.",
      },
      children: [
        {
          id: 9,
          type: "moon",
          name: "Moon",
          map: "moon",
          texture: "2k_moon.jpg",
          category: "Moon",
          color: "#cfcfcf",
          image: "moon.webp",
          radius: 1737,
          distanceFromParent: 384400,
          horizonsId: "301",
          info: {
            mass: "7.342 × 10²² kg",
            gravity: 1.62,
            temperature: -20,
            dayLength: "27.3 Earth days",
            yearLength: "27.3 days",
            orbitalSpeed: 1.0,
            axialTilt: 1.54,
            poleRA: 269.99,
            poleDec: 66.54,
            eccentricity: 0.0549,
            magneticField: false,
            rings: false,
            atmosphere: [],
            funFact: "The Moon is slowly drifting away from Earth at about 3.8 cm per year.",
          },
          children: [],
        },
        {
          id: 33,
          type: "spacecraft",
          category: "Spacecraft",
          name: "James Webb",
          map: "jwst",
          texture: "",
          color: "#ffd27a",
          image: "",
          radius: 0.01,
          distanceFromParent: 1500000,
          horizonsId: "-170",
          info: factOnlyInfo("The largest space telescope ever launched. It orbits the Sun–Earth L2 point, 1.5 million km from Earth, behind a sunshield the size of a tennis court."),
          mission: {
            agency: "NASA · ESA · CSA",
            launched: "25 Dec 2021",
            status: "Observing from Sun–Earth L2",
            stats: [
              { label: "Mirror", value: "6.5 m" },
              { label: "Sunshield", value: "21 × 14 m" },
              { label: "Operating temp", value: "−233 °C" },
            ],
          },
          children: [],
        },
      ],
    },
    {
      id: 4,
      type: "planet",
      name: "Mars",
      map: "mars",
      texture: "2k_mars.jpg",
      category: "Terrestrial planet",
      color: "#e0664a",
      image: "mars.webp",
      radius: 3389.5,
      distanceFromParent: 227900000,
      horizonsId: "499",
      orbitId: "4",
      info: {
        mass: "6.417 × 10²³ kg",
        gravity: 3.72,
        temperature: -65,
        dayLength: "24h 37m",
        yearLength: "687 days",
        orbitalSpeed: 24.1,
        axialTilt: 25.19,
        poleRA: 317.68,
        poleDec: 52.89,
        spinW0: 176.63,
        spinRate: 350.8919830,
        eccentricity: 0.0935,
        magneticField: false,
        rings: false,
        atmosphere: ["CO₂ 95.3%", "N₂ 2.7%", "Ar 1.6%"],
        funFact: "Home to Olympus Mons, the tallest volcano in the Solar System at 21.9 km high.",
      },
      children: [
        {
          id: 10,
          type: "moon",
          name: "Phobos",
          map: "phobos",
          texture: "2k_phobos.jpg",
          category: "Moon",
          color: "#a89a8c",
          image: "",
          radius: 11.267,
          distanceFromParent: 9376,
          horizonsId: "401",
          info: {
            mass: "1.066 × 10¹⁶ kg",
            gravity: 0.0057,
            temperature: -40,
            dayLength: "7h 39m",
            yearLength: "0.319 days",
            orbitalSpeed: 2.14,
            axialTilt: 0,
            eccentricity: 0.0151,
            magneticField: false,
            rings: false,
            atmosphere: [],
            funFact: "Phobos orbits Mars faster than Mars rotates, rising in the west and setting in the east.",
          },
          children: [],
        },
        {
          id: 11,
          type: "moon",
          name: "Deimos",
          map: "deimos",
          texture: "2k_deimos.jpg",
          category: "Moon",
          color: "#b3a596",
          image: "",
          radius: 6.2,
          distanceFromParent: 23463,
          horizonsId: "402",
          info: {
            mass: "1.476 × 10¹⁵ kg",
            gravity: 0.003,
            temperature: -40,
            dayLength: "30h 18m",
            yearLength: "1.263 days",
            orbitalSpeed: 1.35,
            axialTilt: 0,
            eccentricity: 0.00033,
            magneticField: false,
            rings: false,
            atmosphere: [],
            funFact: "Deimos is one of the smallest moons in the Solar System, only about 6 km in radius.",
          },
          children: [],
        },
      ],
    },
    {
      id: 5,
      type: "planet",
      name: "Jupiter",
      map: "jupiter",
      texture: "2k_jupiter.jpg",
      category: "Gas giant",
      color: "#d9b38c",
      image: "jupiter.webp",
      radius: 69911,
      distanceFromParent: 778500000,
      horizonsId: "599",
      orbitId: "5",
      info: {
        mass: "1.898 × 10²⁷ kg",
        gravity: 24.79,
        temperature: -110,
        dayLength: "9h 56m",
        yearLength: "4,333 days",
        orbitalSpeed: 13.1,
        axialTilt: 3.13,
        poleRA: 268.06,
        poleDec: 64.50,
        spinW0: 284.95,
        spinRate: 870.5360000,
        eccentricity: 0.0489,
        magneticField: true,
        rings: true,
        atmosphere: ["H₂ 89.8%", "He 10.2%"],
        funFact: "Jupiter's Great Red Spot is a storm larger than Earth that has been raging for over 350 years.",
      },
      children: [
        {
          id: 12,
          type: "moon",
          name: "Io",
          map: "io",
          texture: "2k_io.jpg",
          category: "Moon",
          color: "#e8d36a",
          image: "io.webp",
          radius: 1821.6,
          distanceFromParent: 421700,
          horizonsId: "501",
          info: {
            mass: "8.93×10²² kg",
            gravity: 1.796,
            temperature: -143,
            dayLength: "1.77 days (tidal locked)",
            yearLength: "1.77 days",
            orbitalSpeed: 17.334,
            axialTilt: 0.04,
            eccentricity: 0.0041,
            magneticField: false,
            rings: false,
            atmosphere: ["SO₂"],
            funFact: "Most volcanically active body in the Solar System",
          },
          children: [],
        },
        {
          id: 13,
          type: "moon",
          name: "Europa",
          map: "europa",
          texture: "2k_europa.jpg",
          category: "Moon",
          color: "#d9cdb8",
          image: "europa.webp",
          radius: 1560.8,
          distanceFromParent: 671034,
          horizonsId: "502",
          info: {
            mass: "4.80×10²² kg",
            gravity: 1.314,
            temperature: -160,
            dayLength: "3.55 days (tidal locked)",
            yearLength: "3.55 days",
            orbitalSpeed: 13.740,
            axialTilt: 0.1,
            eccentricity: 0.009,
            magneticField: false,
            rings: false,
            atmosphere: ["O₂"],
            funFact: "Has a subsurface ocean that may harbor conditions suitable for life",
          },
          children: [],
        },
        {
          id: 14,
          type: "moon",
          name: "Ganymede",
          map: "ganymede",
          texture: "2k_ganymede.jpg",
          category: "Moon",
          color: "#a89f94",
          image: "ganymede.webp",
          radius: 2634.1,
          distanceFromParent: 1070412,
          horizonsId: "503",
          info: {
            mass: "1.48×10²³ kg",
            gravity: 1.428,
            temperature: -163,
            dayLength: "7.15 days (tidal locked)",
            yearLength: "7.15 days",
            orbitalSpeed: 10.880,
            axialTilt: 0.2,
            eccentricity: 0.0013,
            magneticField: true,
            rings: false,
            atmosphere: ["O₂"],
            funFact: "Largest moon in the Solar System, bigger than Mercury",
          },
          children: [],
        },
        {
          id: 15,
          type: "moon",
          name: "Callisto",
          map: "callisto",
          texture: "2k_callisto.jpg",
          category: "Moon",
          color: "#8c8278",
          image: "callisto.webp",
          radius: 2410.3,
          distanceFromParent: 1882709,
          horizonsId: "504",
          info: {
            mass: "1.08×10²³ kg",
            gravity: 1.235,
            temperature: -139,
            dayLength: "16.69 days (tidal locked)",
            yearLength: "16.69 days",
            orbitalSpeed: 8.204,
            axialTilt: 0.2,
            eccentricity: 0.0074,
            magneticField: false,
            rings: false,
            atmosphere: ["CO₂"],
            funFact: "Most heavily cratered object in the Solar System",
          },
          children: [],
        },
      ],
    },
    {
      id: 6,
      type: "planet",
      name: "Saturn",
      map: "saturn",
      texture: "2k_saturn.jpg",
      category: "Gas giant",
      color: "#e8d49a",
      image: "saturn.webp",
      radius: 58232,
      distanceFromParent: 1433000000,
      horizonsId: "699",
      orbitId: "6",
      info: {
        mass: "5.683 × 10²⁶ kg",
        gravity: 10.44,
        temperature: -140,
        dayLength: "10h 42m",
        yearLength: "10,759 days",
        orbitalSpeed: 9.7,
        axialTilt: 26.73,
        poleRA: 40.60,
        poleDec: 83.54,
        spinW0: 38.90,
        spinRate: 810.7939024,
        eccentricity: 0.0565,
        magneticField: true,
        rings: true,
        atmosphere: ["H₂ 96.3%", "He 3.25%"],
        funFact: "Saturn's density is so low that it would float in water if there were an ocean large enough.",
      },
      children: [
        {
          id: 16,
          type: "moon",
          name: "Titan",
          map: "titan",
          texture: "2k_titan.jpg",
          category: "Moon",
          color: "#e3b865",
          image: "titan.webp",
          radius: 2574.7,
          distanceFromParent: 1221870,
          horizonsId: "606",
          info: {
            mass: "1.35×10²³ kg",
            gravity: 1.352,
            temperature: -179,
            dayLength: "15.95 days (tidal locked)",
            yearLength: "15.95 days",
            orbitalSpeed: 5.57,
            axialTilt: 0.3,
            eccentricity: 0.0288,
            magneticField: false,
            rings: false,
            atmosphere: ["N₂", "CH₄"],
            funFact: "Only moon with a dense atmosphere, has methane lakes and seas",
          },
          children: [],
        },
        {
          id: 17,
          type: "moon",
          name: "Enceladus",
          map: "enceladus",
          texture: "2k_enceladus.jpg",
          category: "Moon",
          color: "#f2f4f7",
          image: "",
          radius: 252.1,
          distanceFromParent: 237948,
          horizonsId: "602",
          info: {
            mass: "1.08×10²⁰ kg",
            gravity: 0.113,
            temperature: -201,
            dayLength: "1.37 days (tidal locked)",
            yearLength: "1.37 days",
            orbitalSpeed: 12.63,
            axialTilt: 0.0,
            eccentricity: 0.0047,
            magneticField: false,
            rings: false,
            atmosphere: ["H₂O"],
            funFact: "Geysers of water ice erupt from its south pole into space",
          },
          children: [],
        },
        {
          id: 18,
          type: "moon",
          name: "Mimas",
          map: "mimas",
          texture: "2k_mimas.jpg",
          category: "Moon",
          color: "#c8c8c8",
          image: "",
          radius: 198.2,
          distanceFromParent: 185539,
          horizonsId: "601",
          info: {
            mass: "3.75×10¹⁹ kg",
            gravity: 0.064,
            temperature: -209,
            dayLength: "0.94 days (tidal locked)",
            yearLength: "0.94 days",
            orbitalSpeed: 14.28,
            axialTilt: 0.0,
            eccentricity: 0.0196,
            magneticField: false,
            rings: false,
            atmosphere: [],
            funFact: "Its giant Herschel crater makes it resemble the Death Star",
          },
          children: [],
        },
        {
          id: 19,
          type: "moon",
          name: "Rhea",
          map: "rhea",
          texture: "2k_rhea.jpg",
          category: "Moon",
          color: "#d0ccc6",
          image: "",
          radius: 763.8,
          distanceFromParent: 527108,
          horizonsId: "605",
          info: {
            mass: "2.31×10²¹ kg",
            gravity: 0.264,
            temperature: -174,
            dayLength: "4.52 days (tidal locked)",
            yearLength: "4.52 days",
            orbitalSpeed: 8.48,
            axialTilt: 0.3,
            eccentricity: 0.0012,
            magneticField: false,
            rings: false,
            atmosphere: ["O₂"],
            funFact: "Second largest moon of Saturn with a wispy ice surface",
          },
          children: [],
        },
        {
          id: 20,
          type: "moon",
          name: "Iapetus",
          map: "iapetus",
          texture: "2k_iapetus.jpg",
          category: "Moon",
          color: "#b8a07a",
          image: "",
          radius: 734.5,
          distanceFromParent: 3560820,
          horizonsId: "608",
          info: {
            mass: "1.81×10²¹ kg",
            gravity: 0.223,
            temperature: -143,
            dayLength: "79.33 days (tidal locked)",
            yearLength: "79.33 days",
            orbitalSpeed: 3.26,
            axialTilt: 15.47,
            eccentricity: 0.0286,
            magneticField: false,
            rings: false,
            atmosphere: [],
            funFact: "Has a striking two-tone coloring — one half dark, the other bright white",
          },
          children: [],
        },
      ],
    },
    {
      id: 7,
      type: "planet",
      name: "Uranus",
      map: "uranus",
      texture: "2k_uranus.jpg",
      category: "Ice giant",
      color: "#9fe3e0",
      image: "uranus.webp",
      radius: 25362,
      distanceFromParent: 2871000000,
      horizonsId: "799",
      orbitId: "7",
      info: {
        mass: "8.681 × 10²⁵ kg",
        gravity: 8.87,
        temperature: -195,
        dayLength: "17h 14m",
        yearLength: "30,687 days",
        orbitalSpeed: 6.8,
        axialTilt: 97.77,
        poleRA: 257.31,
        poleDec: -15.18,
        spinW0: 203.81,
        spinRate: -501.1600928,
        eccentricity: 0.0457,
        magneticField: true,
        rings: true,
        atmosphere: ["H₂ 82.5%", "He 15.2%", "CH₄ 2.3%"],
        funFact: "Uranus rotates on its side with an axial tilt of 98°, likely caused by a collision with an Earth-sized object.",
      },
      children: [
        {
          id: 21,
          type: "moon",
          name: "Miranda",
          map: "miranda",
          texture: "2k_miranda.jpg",
          category: "Moon",
          color: "#bdbdbd",
          image: "",
          radius: 235.8,
          distanceFromParent: 129390,
          horizonsId: "705",
          info: {
            mass: "6.59×10¹⁹ kg",
            gravity: 0.079,
            temperature: -213,
            dayLength: "1.41 days (tidal locked)",
            yearLength: "1.41 days",
            orbitalSpeed: 6.66,
            axialTilt: 4.34,
            eccentricity: 0.0013,
            magneticField: false,
            rings: false,
            atmosphere: [],
            funFact: "Has extreme geological features including a 20km deep canyon",
          },
          children: [],
        },
        {
          id: 22,
          type: "moon",
          name: "Ariel",
          map: "ariel",
          texture: "2k_ariel.jpg",
          category: "Moon",
          color: "#c9c9c9",
          image: "",
          radius: 578.9,
          distanceFromParent: 191020,
          horizonsId: "701",
          info: {
            mass: "1.35×10²¹ kg",
            gravity: 0.269,
            temperature: -213,
            dayLength: "2.52 days (tidal locked)",
            yearLength: "2.52 days",
            orbitalSpeed: 5.51,
            axialTilt: 0.0,
            eccentricity: 0.0012,
            magneticField: false,
            rings: false,
            atmosphere: [],
            funFact: "Brightest and youngest surface of all Uranian moons",
          },
          children: [],
        },
        {
          id: 23,
          type: "moon",
          name: "Umbriel",
          map: "umbriel",
          texture: "2k_umbriel.jpg",
          category: "Moon",
          color: "#8f8f8f",
          image: "",
          radius: 584.7,
          distanceFromParent: 266300,
          horizonsId: "702",
          info: {
            mass: "1.17×10²¹ kg",
            gravity: 0.234,
            temperature: -213,
            dayLength: "4.14 days (tidal locked)",
            yearLength: "4.14 days",
            orbitalSpeed: 4.67,
            axialTilt: 0.0,
            eccentricity: 0.0039,
            magneticField: false,
            rings: false,
            atmosphere: [],
            funFact: "Darkest of the large Uranian moons",
          },
          children: [],
        },
        {
          id: 24,
          type: "moon",
          name: "Titania",
          map: "titania",
          texture: "2k_titania.jpg",
          category: "Moon",
          color: "#bfb7ae",
          image: "",
          radius: 788.4,
          distanceFromParent: 435910,
          horizonsId: "703",
          info: {
            mass: "3.53×10²¹ kg",
            gravity: 0.379,
            temperature: -213,
            dayLength: "8.71 days (tidal locked)",
            yearLength: "8.71 days",
            orbitalSpeed: 3.64,
            axialTilt: 0.0,
            eccentricity: 0.0011,
            magneticField: false,
            rings: false,
            atmosphere: [],
            funFact: "Largest moon of Uranus, named after the queen of fairies",
          },
          children: [],
        },
        {
          id: 25,
          type: "moon",
          name: "Oberon",
          map: "oberon",
          texture: "2k_oberon.jpg",
          category: "Moon",
          color: "#b0a69c",
          image: "",
          radius: 761.4,
          distanceFromParent: 583519,
          horizonsId: "704",
          info: {
            mass: "3.01×10²¹ kg",
            gravity: 0.346,
            temperature: -213,
            dayLength: "13.46 days (tidal locked)",
            yearLength: "13.46 days",
            orbitalSpeed: 3.15,
            axialTilt: 0.0,
            eccentricity: 0.0014,
            magneticField: false,
            rings: false,
            atmosphere: [],
            funFact: "Outermost major moon of Uranus with large impact craters",
          },
          children: [],
        },
      ],
    },
    {
      id: 8,
      type: "planet",
      name: "Neptune",
      map: "neptune",
      texture: "2k_neptune.jpg",
      category: "Ice giant",
      color: "#5b7cff",
      image: "neptune.webp",
      radius: 24622,
      distanceFromParent: 4495000000,
      horizonsId: "899",
      orbitId: "8",
      info: {
        mass: "1.024 × 10²⁶ kg",
        gravity: 11.15,
        temperature: -200,
        dayLength: "16h 6m",
        yearLength: "60,190 days",
        orbitalSpeed: 5.4,
        axialTilt: 28.32,
        poleRA: 299.36,
        poleDec: 43.46,
        spinW0: 253.18,
        spinRate: 536.3128492,
        eccentricity: 0.0113,
        magneticField: true,
        rings: true,
        atmosphere: ["H₂ 80%", "He 19%", "CH₄ 1.5%"],
        funFact: "Neptune has the strongest winds in the Solar System, reaching up to 2,100 km/h.",
      },
      children: [
        {
          id: 26,
          type: "moon",
          name: "Triton",
          map: "triton",
          texture: "2k_triton.jpg",
          category: "Moon",
          color: "#d8c8c0",
          image: "triton.webp",
          radius: 1353.4,
          distanceFromParent: 354759,
          horizonsId: "801",
          info: {
            mass: "2.14×10²² kg",
            gravity: 0.779,
            temperature: -235,
            dayLength: "5.88 days (retrograde, tidal locked)",
            yearLength: "5.88 days",
            orbitalSpeed: 4.39,
            axialTilt: 0.0,
            eccentricity: 0.000016,
            magneticField: false,
            rings: false,
            atmosphere: ["N₂"],
            funFact: "Only large moon with a retrograde orbit, likely a captured Kuiper Belt object",
          },
          children: [],
        },
      ],
    },
    {
      id: 34,
      type: "region",
      category: "Asteroid belt",
      name: "Asteroid Belt",
      map: "asteroid-belt",
      texture: "",
      color: "#b8a88f",
      image: "asteroid-belt.webp",
      radius: 0,
      distanceFromParent: 411000000,
      horizonsId: "",
      info: {
        ...factOnlyInfo("Despite the movies, the belt is mostly empty space: asteroids are on average about a million kilometres apart, and spacecraft cross it without having to dodge anything."),
        mass: "≈ 2.4 × 10²¹ kg",
      },
      region: {
        innerAU: 2.1,
        outerAU: 3.3,
        headline: [
          { label: "Where", value: "Between Mars and Jupiter" },
          { label: "Distance", value: "2.1–3.3 AU from the Sun" },
          { label: "Mass", value: "≈ 3% of the Moon" },
        ],
        stats: [
          { label: "Asteroids > 1 km", value: "1–2 million" },
          { label: "Largest", value: "Ceres" },
          { label: "Orbit", value: "3–6 years" },
        ],
      },
      children: [],
    },
    {
      id: 27,
      type: "planet",
      category: "Dwarf planet",
      name: "Ceres",
      map: "ceres",
      texture: "2k_ceres.jpg",
      color: "#a8a8a8",
      image: "",
      radius: 469.7,
      distanceFromParent: 413700000,
      horizonsId: "2000001",
      info: {
        mass: "9.38 × 10²⁰ kg",
        gravity: 0.28,
        temperature: -105,
        dayLength: "9h 4m",
        yearLength: "1,682 days",
        orbitalSpeed: 17.9,
        axialTilt: 4,
        poleRA: 291.418,
        poleDec: 66.764,
        spinW0: 170.65,
        spinRate: 952.1532,
        eccentricity: 0.0785,
        magneticField: false,
        rings: false,
        atmosphere: [],
        funFact: "The largest object in the asteroid belt and the only dwarf planet in the inner Solar System. Its bright spots are salt deposits.",
      },
      children: [],
    },
    {
      id: 28,
      type: "planet",
      category: "Dwarf planet",
      name: "Pluto",
      map: "pluto",
      texture: "2k_pluto.jpg",
      color: "#d8c2a8",
      image: "",
      radius: 1188.3,
      distanceFromParent: 5906400000,
      horizonsId: "999",
      orbitId: "9",
      barycenter: { satelliteId: "901", massRatio: 0.10855 },
      info: {
        mass: "1.303 × 10²² kg",
        gravity: 0.62,
        temperature: -229,
        dayLength: "6.39 Earth days",
        yearLength: "248 years",
        orbitalSpeed: 4.74,
        axialTilt: 122.53,
        poleRA: 132.993,
        poleDec: -6.163,
        spinW0: 302.695,
        spinRate: -56.3625225,
        eccentricity: 0.2488,
        magneticField: false,
        rings: false,
        atmosphere: ["N₂", "CH₄", "CO"],
        funFact: "Pluto's heart-shaped Sputnik Planitia is a basin of frozen nitrogen larger than Texas, first seen by New Horizons in 2015.",
      },
      children: [
        {
          id: 29,
          type: "moon",
          category: "Moon",
          name: "Charon",
          map: "charon",
          texture: "2k_charon.jpg",
          color: "#b0aaa5",
          image: "",
          radius: 606,
          distanceFromParent: 19591,
          horizonsId: "901",
          info: {
            mass: "1.586 × 10²¹ kg",
            gravity: 0.288,
            temperature: -220,
            dayLength: "6.39 Earth days",
            yearLength: "6.39 days",
            orbitalSpeed: 0.21,
            axialTilt: 0,
            poleRA: 132.993,
            poleDec: -6.163,
            eccentricity: 0.0002,
            magneticField: false,
            rings: false,
            atmosphere: [],
            funFact: "Charon is so big compared to Pluto that the two orbit a point in space between them, always showing each other the same face.",
          },
          children: [],
        },
      ],
    },
    {
      id: 30,
      type: "spacecraft",
      category: "Spacecraft",
      name: "Voyager 1",
      map: "voyager-1",
      texture: "",
      color: "#7fffd4",
      image: "",
      radius: 0.01,
      distanceFromParent: 25000000000,
      horizonsId: "-31",
      info: factOnlyInfo("The most distant human-made object. It carries the Golden Record, with sounds and images of life on Earth."),
      mission: {
        agency: "NASA",
        launched: "5 Sep 1977",
        status: "Interstellar space since 2012",
        stats: [
          { label: "Flybys", value: "Jupiter, Saturn" },
          { label: "Speed", value: "17 km/s" },
        ],
      },
      children: [],
    },
    {
      id: 31,
      type: "spacecraft",
      category: "Spacecraft",
      name: "Voyager 2",
      map: "voyager-2",
      texture: "",
      color: "#7fffd4",
      image: "",
      radius: 0.01,
      distanceFromParent: 21000000000,
      horizonsId: "-32",
      info: factOnlyInfo("The only spacecraft to have visited Uranus (1986) and Neptune (1989)."),
      mission: {
        agency: "NASA",
        launched: "20 Aug 1977",
        status: "Interstellar space since 2018",
        stats: [
          { label: "Flybys", value: "Jupiter, Saturn, Uranus, Neptune" },
          { label: "Speed", value: "15 km/s" },
        ],
      },
      children: [],
    },
    {
      id: 32,
      type: "spacecraft",
      category: "Spacecraft",
      name: "New Horizons",
      map: "new-horizons",
      texture: "",
      color: "#7fffd4",
      image: "",
      radius: 0.01,
      distanceFromParent: 9000000000,
      horizonsId: "-98",
      info: factOnlyInfo("The first spacecraft to fly past Pluto (2015) and a Kuiper Belt object, Arrokoth (2019)."),
      mission: {
        agency: "NASA",
        launched: "19 Jan 2006",
        status: "Exploring the Kuiper Belt",
        stats: [
          { label: "Flybys", value: "Jupiter, Pluto, Arrokoth" },
          { label: "Speed", value: "14 km/s" },
        ],
      },
      children: [],
    },
  ],
};

export const MILKY_WAY: CelestialBody = {
  id: 100,
  type: "galaxy",
  category: "Galaxy",
  name: "Milky Way",
  map: "milky-way",
  texture: "",
  color: "#ffffff",
  image: "milky-way.webp",
  radius: 52850,
  distanceFromParent: 0,
  horizonsId: "",
  info: {
    mass: "1.5 × 10¹² solar masses",
    gravity: 0,
    temperature: 0,
    dayLength: "225 million years",
    yearLength: "",
    orbitalSpeed: 220,
    axialTilt: 0,
    eccentricity: 0,
    magneticField: false,
    rings: false,
    atmosphere: [],
    funFact:
      "The Milky Way contains 100-400 billion stars and is about 100,000 light-years in diameter. Our Solar System orbits the galactic center at about 220 km/s.",
  },
  galaxy: {
    diameter: "100,000 light-years",
    kind: "Barred spiral (SBbc)",
    stats: [
      { label: "Stars", value: "100-400 B" },
      { label: "Age", value: "13.6 Gyr" },
      { label: "Arms", value: "4" },
      { label: "Rotation", value: "225 Myr" },
      { label: "Sun dist.", value: "26,000 ly" },
      { label: "Speed", value: "220 km/s" },
    ],
  },
  children: [SOLAR_SYSTEM],
};

// Backward-compatible export: array wrapping the root for 3D rendering code
export const CELESTIAL_BODIES: CelestialBody[] = [SOLAR_SYSTEM];
